### ISSUE TITLE
IaCでもノーコードがしたい！～AWS Glue編～

### ISSUE THREAD

**Issue by WinterYukky** [aws-events/aws-dev-day-online-japan-2022-cfp#56]
### セッションタイトル (必須)

- [X] セッションのタイトルをイシュー件名に最大40文字程度で入力しました

### 連絡先の登録 (必須)

- [X] 私は、[こちらのフォーム](https://pages.awscloud.com/2022_DevDay_CfP_registration.html)に必要事項を記入してsubmitしました

### セッションのアブストラクト (最大250文字) (必須)

時代がノーコードを叫んでいる。そして俺たちはCDKも求めている。
ノーコードとCDK、この相容れない2つの関係に今新しい風が吹こうとしている！

・・・え？ CDKはInfrastructure as Codeだからノーコードじゃない？？ そんなお堅いこと言いなさんな。

※このセッションはCDKの高いポテンシャルを活かし、Glueのジョブスクリプトを自動生成するコンストラクトライブラリを作成した話とその紹介です。

### セッション時間

20分

### 想定受講者の知識レベル（必須）

中級 - セッションの中心となるトピックを触ったことがある、現在勉強中である方向け

### 想定受講者の開発対象やロール・役割 (複数選択可) (必須)

DevOps / Infrastructure as Code

### セッションのトピック (複数選択可) (必須)

DevOps / Infrastructure as Code

### セッションの技術カテゴリー (複数選択可) (必須)

サーバーレス

### セッション内で登場する主な AWS サービス (任意)

AWS CDK, AWS Glue

**Comment by WinterYukky** [comment]
締め切った後になって恐縮です。
こちら、都合が合わなくなったためキャンセルすることは可能でしょうか・・・。

**Comment by G-F** [comment]
ご連絡ありがとうございます。
承知いたしました、大変残念ですがこちらのCFP はクローズとさせていただきます。
